# ~/.vim/rc/dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
	if dein#util#_is_windows()
		let cmd = 'tools\\update-dll-mingw'
	elseif dein#util#_is_cygwin()
		let cmd = 'make -f make_cygwin.mak'
	elseif executable('gmake')
		let cmd = 'gmake'
	else
		let cmd = 'make'
	endif
	let g:dein#pulgin.build = cmd
'''

[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'thinca/vim-quickrun'
[[plugins]]
repo = 'kannokanno/previm'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
