#課題 ~/.vim/rc/dein.toml

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
	if dein#util#_is_windows()
		let cmd = 'tools\\update-dll-mingw'
	elseif dein#util#_is_cygwin()
		let cmd = 'make -f make_cygwin.mak'
	elseif executable('gmake')
		let cmd = 'gmake'
	else
		let cmd = 'make'
	endif
	let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/unite.vim'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'thinca/vim-quickrun'

hook_add = '''
  let g:quickrun_config = get(g:, 'quickrun_config', {})
  let g:quickrun_config['tex'] = {
  \ 'command' : 'latexmk',
  \ 'outputter' : 'error',
  \ 'outputter/error/success' : 'null',
  \ 'outputter/error/error' : 'quickfix',
  \ 'srcfile' : 'main.tex',
  \ 'cmdopt' : '-pdfdvi',
  \ 'hook/sweep/files' : [
  \   '%S:p:r.aux',
  \   '%S:p:r.bbl',
  \   '%S:p:r.blg',
  \   '%S:p:r.dvi',
  \   '%S:p:r.fdb_latexmk',
  \   '%S:p:r.fls',
  \   '%S:p:r.log',
  \   '%S:p:r.out'
  \   ],
  \ 'exec': '%c %o %a %s',
  \}

  let g:quickrun_config.tmptex = {
  \ 'exec' : [
  \   'mv %s %a/tmptex.latex',
  \   'latexmk -pdfdvi -pv -output-directory=%a %a/tmptex.latex',
  \   ],
  \ 'args' : expand("%:p:h:gs?\\\\?/?"),
  \ 'outputter' : 'error',
  \ 'outputter/error/error' : 'quickfix',
  \
  \ 'hook/eval/enable' : 1,
  \ 'hook/eval/cd' : "%s:r",
  \
  \ 'hook/eval/template' : '\documentclass{jsarticle}'
  \   .'\usepackage[dvipdfms]{graphicx, hyperref}'
  \   .'\usepackage{float}'
  \   .'\usepackage{amsmath,amssymb,amsthm,ascmac,mathrsfs}'
  \   .'\allowdisplaybreaks[1]'
  \   .'\theoremstyle{definition}'
  \   .'\newtheorem{theorem}{定理}'
  \   .'\newtheorem*{theorem*}{定理}'
  \   .'\newtheorem{definition}[theorem]{定義}'
  \   .'\newtheorem*{definition*}{定義}'
  \   .'\renewcomand\vector[1]{\mbox{\boldmath{\$#1\$}}}'
  \   .'\begin{document}'
  \   .'%s'
  \   .'\end{document}',
  \
  \ 'hook/sweep/files' : [
  \   '%a/tmptex.latex',
  \   '%a/tmptex.out',
  \   '%a/tmptex.fdb_latexmk',
  \   '%a/tmptex.log',
  \   '%a/tmptex.aux',
  \   '%a/tmptex.dvi'
  \   ],
  \}

  vnoremap <silent><buffer> <F5> :QuickRun -mode v -type tmptex<CR>

  nnoremap <silent><F5> :QuickRun<CR>

  autocmd BufWritePost,FileWritePost *.tex QuickRun tex
'''

[[plugins]]
repo = 'kannokanno/previm'
[[plugins]]
repo = 'tyru/open-browser.vim'
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
[[plugins]]
repo = 'lervag/vimtex'
